"""
Django settings for portfolio_project project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from .env import get_bool, get_list, get_str, load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

# DEBUG defaults to False so that an unconfigured deployment fails closed.
DEBUG = get_bool('DEBUG', default=False)

# SECURITY WARNING: keep the secret key used in production secret!
# In DEBUG a throwaway key keeps `runserver` working with no setup; outside
# DEBUG an unset SECRET_KEY raises at import time rather than shipping a
# publicly-known key.
if DEBUG:
    SECRET_KEY = get_str('SECRET_KEY', 'django-insecure-dev-only-do-not-use-in-production')
else:
    SECRET_KEY = get_str('SECRET_KEY')

ALLOWED_HOSTS = get_list('ALLOWED_HOSTS', 'localhost,127.0.0.1' if DEBUG else '')

# Behind a TLS-terminating proxy these make sessions/CSRF cookies secure-only.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
    X_FRAME_OPTIONS = 'DENY'
    CSRF_TRUSTED_ORIGINS = get_list('CSRF_TRUSTED_ORIGINS')
    # Opt-in: a deployment that is not yet fully HTTPS should leave these off.
    SECURE_SSL_REDIRECT = get_bool('SECURE_SSL_REDIRECT', default=True)
    SECURE_HSTS_SECONDS = int(get_str('SECURE_HSTS_SECONDS', '0'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_HSTS_SECONDS > 0
    SECURE_HSTS_PRELOAD = SECURE_HSTS_SECONDS > 0


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'portfolio',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serves the collected static files *and* admin-uploaded media straight
    # from the app server, so a deployment needs no separate web server or CDN
    # in front of it. Must sit immediately after SecurityMiddleware.
    'portfolio_project.middleware.WhiteNoiseWithMediaMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'portfolio_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'portfolio.context_processors.site',
            ],
        },
    },
]

WSGI_APPLICATION = 'portfolio_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

# In production, hash every static filename and gzip/brotli it at collect
# time, so assets can be cached forever and a deploy busts the cache by
# itself. Left off in DEBUG, where `runserver` serves the source tree and a
# manifest would require a collectstatic run before every page load.
if not DEBUG:
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }

# Media files configuration
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# WhiteNoise scans its roots once at start-up unless told otherwise, which
# would leave an image uploaded through the admin 404ing until the next
# restart. The extra stat() per request is irrelevant at this site's traffic,
# and an admin upload that silently does not appear is not.
WHITENOISE_AUTOREFRESH = get_bool('WHITENOISE_AUTOREFRESH', default=True)

# Site identity, used for page titles and social/link previews.
# Positioning follows the résumé (static/files/): "Aspiring DevOps Engineer |
# Python | Cloud | Automation". A site that sells a different role from the CV
# a recruiter is reading alongside it undercuts both.
SITE_OWNER = get_str('SITE_OWNER', 'Anand N')
SITE_ROLE = get_str('SITE_ROLE', 'Aspiring DevOps Engineer')
SITE_TAGLINE = get_str('SITE_TAGLINE', 'Python · Cloud · Automation')
SITE_DESCRIPTION = get_str(
    'SITE_DESCRIPTION',
    'Computer Science Engineering graduate with a strong foundation in Python, '
    'Git and Linux, building practical DevOps skills across CI/CD, Docker, '
    'Jenkins and AWS.',
)
# Absolute site URL, used for canonical and Open Graph tags.
SITE_URL = get_str('SITE_URL', '')

# Contact and social links. These are read by the site context processor and
# rendered in the hero, contact section and footer, so they are configured in
# one place instead of being repeated across templates.
SITE_EMAIL = get_str('SITE_EMAIL', 'anandanand6776@gmail.com')
# Already published in the downloadable résumé; set to an empty value to omit
# it from the page.
SITE_PHONE = get_str('SITE_PHONE', '+91 7306922640')
SITE_GITHUB_URL = get_str('SITE_GITHUB_URL', 'https://github.com/900Gang')
SITE_LINKEDIN_URL = get_str('SITE_LINKEDIN_URL', 'https://linkedin.com/in/anand-n-anand-n')
SITE_LOCATION = get_str('SITE_LOCATION', 'Kerala, India')
SITE_FOCUS = get_str('SITE_FOCUS', 'DevOps, cloud and Python automation')

# Shown as the availability pill in the hero. Set to an empty string to hide
# it — a stale "open to work" badge is worse than none.
SITE_AVAILABILITY = get_str('SITE_AVAILABILITY', 'Open to opportunities')

# Path inside the static files tree. The download button appears only once
# this file actually exists.
RESUME_STATIC_PATH = get_str('RESUME_STATIC_PATH', 'files/Anand_Python_Dev_Final.pdf')
# Filename the visitor's browser saves it as. The working filename on disk is
# not what a recruiter should end up with in their downloads folder.
RESUME_DOWNLOAD_NAME = get_str('RESUME_DOWNLOAD_NAME', 'Anand_N_Resume.pdf')

# Link-preview image, resolved the same way as the resume: absent file, no
# tag. Regenerate with `python manage.py make_og_image`.
OG_IMAGE_STATIC_PATH = get_str('OG_IMAGE_STATIC_PATH', 'img/og-image.png')


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
