# Generated by Django 5.2.17 on 2026-09-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_certification_professionalskill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('devops', 'DevOps & Cloud'), ('backend', 'Backend & Data'), ('frontend', 'Web & Frontend'), ('testing', 'Testing & Process'), ('tools', 'Tools & Workflow'), ('concepts', 'Core Concepts')], default='concepts', max_length=20),
        ),
    ]
